apiVersion: apps/v1
kind: Deployment

metadata:
  name: hook
  namespace: nau-ai

  labels:
    app: hook
    project: nau-ai

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hook

  template:
    metadata:
      labels:
        app: hook

    spec:
      containers:
        - name: hook

          image: alexisbaladon/nau_hook:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 1235

          env:
            - name: HOST
              value: "0.0.0.0"

            - name: PORT
              value: "1235"

          envFrom:
            - configMapRef:
                name: nau-config

            - secretRef:
                name: nau-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 1235

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 1235

            initialDelaySeconds: 15
            periodSeconds: 20