apiVersion: v1
kind: Service

metadata:
  name: hook
  namespace: nau-ai

  labels:
    app: hook
    project: nau-ai

spec:
  type: ClusterIP

  selector:
    app: hook

  ports:
    - protocol: TCP
      port: 1235
      targetPort: 1235