apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: nau-ai

  labels:
    app: frontend
    project: nau-ai

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: alexisbaladon/nau_frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5173

          env:
            - name: HOST
              value: "0.0.0.0"

            - name: PORT
              value: "5173"

          envFrom:
            - configMapRef:
                name: nau-config
            
            - secretRef:
                name: nau-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 5173

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 5173

            initialDelaySeconds: 15
            periodSeconds: 20