apiVersion: apps/v1
kind: Deployment

metadata:
  name: filter
  namespace: nau-ai

spec:
  replicas: 1

  selector:
    matchLabels:
      app: filter

  template:
    metadata:
      labels:
        app: filter

    spec:
      containers:
        - name: filter

          image: alexisbaladon/nau_filter:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 1237

          env:
            - name: HOST
              value: "0.0.0.0"

            - name: PORT
              value: "1237"

          envFrom:
            - configMapRef:
                name: nau-config

            - secretRef:
                name: nau-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 1237

          livenessProbe:
            httpGet:
              path: /health
              port: 1237