from flask import (
    Flask, 
    jsonify, 
    request, 
    Response, 
    stream_with_context,
    abort,
    send_from_directory,
)
from langchain_openai import ChatOpenAI

from mcp_adapters.chessboard_renderer import all_tools
from constants import HOST, PORT, DEBUG, TOOLS_IMAGES_DIR
from agent_handler import (
    build_messages,
    generate_and_trace,
    stream_response,
)

import os


app = Flask(__name__)
llm = ChatOpenAI(
    model="gpt-4.1-mini",
    temperature=0,
    streaming=True,
)

@app.route("/generate", methods=["POST"])
def generate():
    body = request.get_json(silent=True) or {}

    raw_messages = body.get("messages", [])
    stream = body.get("stream", False)
    tracing_headers = body.get("tracing_headers", {})
    user_id = body.get("user_id", "default")
    selected_tools = body.get("tools")
    selected_tool_mapping = {tool_name: all_tools[tool_name] for tool_name in selected_tools}

    if not raw_messages:
        return jsonify({
            "error": "messages is required"
        }), 400

    try:
        messages = build_messages(raw_messages)
    except ValueError as exc:
        return jsonify({"error": str(exc)}), 400
    if stream:
        return Response(
            stream_with_context(
                stream_response(
                    llm, 
                    messages, 
                    tool_mapping=selected_tool_mapping,
                    user_id=user_id,
                    langsmith_extra={"parent": tracing_headers}
                )
            ),
            mimetype="text/event-stream",
        )
    
    result, status_code = generate_and_trace(
        llm, 
        messages, 
        user_id=user_id, 
        tool_mapping=selected_tool_mapping
    )

    return jsonify(result), status_code


"""
TODO: Divide responsibilities of the agent and the tool that stores images, 
and create a new microservice or module for image generation/storage.
"""
@app.route("/image/<path:filename>", methods=["GET"])
def get_image(filename):
    """
    Returns an SVG image previously generated by the chess tool.
    """

    safe_path = os.path.abspath(TOOLS_IMAGES_DIR)
    requested_path = os.path.abspath(
        os.path.join(safe_path, filename)
    )

    # Prevent directory traversal attacks
    if not requested_path.startswith(safe_path):
        abort(403)

    if not os.path.exists(requested_path):
        abort(404)

    return send_from_directory(
        safe_path,
        filename,
        mimetype="image/svg+xml",
    )


@app.route("/health")
def health():
    return {"status": "ok"}, 200


if __name__ == "__main__":
    app.run(
    host=HOST,
    port=PORT,
    debug=DEBUG,
)
