from flask import (
    Flask, 
    jsonify, 
    request, 
    Response, 
    stream_with_context,
    abort,
    send_from_directory,
)
from langchain_openai import ChatOpenAI

from tools import create_chess_board_image_tool
from constants import HOST, PORT, DEBUG, TOOLS_IMAGES_DIR
from agent_handler import (
    build_messages,
    generate_and_trace,
    stream_response,
)

import os


app = Flask(__name__)

llm = ChatOpenAI(
    model="gpt-4.1-mini",
    temperature=0,
    streaming=True,
).bind_tools(
    [
        create_chess_board_image_tool,
    ]
)

tools = {"create_chess_board_image_tool": create_chess_board_image_tool}

@app.route("/generate", methods=["POST"])
def generate():
    body = request.get_json(silent=True) or {}

    raw_messages = body.get("messages", [])
    stream = body.get("stream", False)

    if not raw_messages:
        return jsonify({
            "error": "messages is required"
        }), 400

    try:
        messages = build_messages(raw_messages)
    except ValueError as exc:
        return jsonify({"error": str(exc)}), 400
    if stream:
        return Response(
            stream_with_context(stream_response(llm, messages, tools=tools)),
            mimetype="text/event-stream",
        )
    result, status_code = generate_and_trace(llm, messages, tools=tools)

    return jsonify(result), status_code


# Used for agent tool image creation.
@app.route("/image/<path:filename>", methods=["GET"])
def get_image(filename):
    """
    Returns an SVG image previously generated by the chess tool.
    """

    safe_path = os.path.abspath(TOOLS_IMAGES_DIR)
    requested_path = os.path.abspath(
        os.path.join(safe_path, filename)
    )

    # Prevent directory traversal attacks
    if not requested_path.startswith(safe_path):
        abort(403)

    if not os.path.exists(requested_path):
        abort(404)

    return send_from_directory(
        safe_path,
        filename,
        mimetype="image/svg+xml",
    )


@app.route("/health")
def health():
    return {"status": "ok"}, 200


if __name__ == "__main__":
    app.run(
    host=HOST,
    port=PORT,
    debug=DEBUG,
)
